export const ROGUETRADER = {};

ROGUETRADER.Attributes = {
  "weaponskill"   : {name: "Weapon Skill",    abbrev: "WS"},
  "ballisticskill": {name: "Ballistic Skill", abbrev: "BS"},
  "strength"      : {name: "Strength",        abbrev: "S"},
  "toughness"     : {name: "Toughness",       abbrev: "T"},
  "agility"       : {name: "Agility",         abbrev: "Agi"},
  "intelligence"  : {name: "Intelligence",    abbrev: "Int"},
  "perception"    : {name: "Perception",      abbrev: "Per"},
  "willpower"     : {name: "Willpower",       abbrev: "WP"},
  "fellowship"    : {name: "Fellowship",      abbrev: "Fel"},
  "influence"     : {name: "Influence",       abbrev: "Inf"},
}

ROGUETRADER.Skills = {
  "acrobatics"          :  {name: "Acrobatics",         attribute: "agility"},
  "athletics"           :  {name: "Athletics",          attribute: "strength"},
  "awareness"           :  {name: "Awareness",          attribute: "perception"},
  "charm"               :  {name: "Charm",              attribute: "fellowship"},
  "command"             :  {name: "Command",            attribute: "fellowship"},
  "commerce"            :  {name: "Commerce",           attribute: "fellowship"},
  "deceive"             :  {name: "Deceive",            attribute: "fellowship"},
  "dodge"               :  {name: "Dodge",              attribute: "agility"},
  "inquiry"             :  {name: "Inquiry",            attribute: "fellowship"},
  "interrogation"       :  {name: "Interrogation",      attribute: "willpower"},
  "intimidate"          :  {name: "Intimidate",         attribute: "strength"},
  "logic"               :  {name: "Logic",              attribute: "intelligence"},
  "medicae"             :  {name: "Medicae",            attribute: "intelligence"},
  "navigatesurface"     :  {name: "Navigate(surface)",  attribute: "intelligence"},
  "navigatestellar"     :  {name: "Navigate(stellar)",  attribute: "intelligence"},
  "navigatewarp"        :  {name: "Navigate(warp)",     attribute: "intelligence"},
  "operateaeronautica"  :  {name: "Operate(aero)",      attribute: "agility"},
  "operatesurface"      :  {name: "Operate(surface)",   attribute: "agility"},
  "operatevoidship"     :  {name: "Operate(voidship)",  attribute: "agility"},
  "parry"               :  {name: "Parry",              attribute: "weaponskill"},
  "psyniscience"        :  {name: "Psyniscience",       attribute: "willpower"},
  "scrutiny"            :  {name: "Scrutiny",           attribute: "perception"},
  "security"            :  {name: "Security",           attribute: "intelligence"},
  "sleightofhand"       :  {name: "Sleight of hand",    attribute: "agility"},
  "stealth"             :  {name: "Stealth",            attribute: "agility"},
  "survival"            :  {name: "Survival",           attribute: "perception"},
  "techuse"             :  {name: "Tech-use",           attribute: "intelligence"},
  "trade"               :  {name: "Trade",              attribute: "intelligence"},
};

ROGUETRADER.rankVal = {
  0: -20,
  1: 10,
  2: 20,
  3: 30,
  4: 40
}

ROGUETRADER.testDiff = {
  "Trivial (+60)"     : 60,
  "Elementary (+50)"  : 50,
  "Simple (+40)"      : 40,
  "Easy (+30)"        : 30,
  "Routine (+20)"     : 20,
  "Ordinary (+10)"    : 10,
  "Challenging (+0)"  : 0,
  "Difficult (-10)"   : -10,
  "Hard (-20)"        : -20,
  "Very Hard (-30)"   : -30,
  "Arduous (-40)"     : -40,
  "Punishing (-50)"   : -50,
  "Hellish (-60)"     : -60,
};

//TODO: remove this (used once in item-sheet.mjs)
ROGUETRADER.specialistNameCat = {
  "common"      : "commonLoreOptions",
  "scholastic"  : "ScholasticLoreOptions",
  "forbidden"   : "ForbiddenLoreOptions",
  "linguistics" : "LinguisticsOptions"
}

//TODO: hook up to this instead
ROGUETRADER.specialistSkillOptions = {
  "common"      : {name: "Common Lore",     abbrev: "CL",   attribute: "intelligence", options: "commonLoreOptions"},
  "scholastic"  : {name: "Scholastic Lore", abbrev: "SL",   attribute: "intelligence", options: "ScholasticLoreOptions"},
  "forbidden"   : {name: "Forbidden Lore",  abbrev: "FL",   attribute: "intelligence", options: "ForbiddenLoreOptions"},
  "linguistics" : {name: "Linguistics",     abbrev: "Lng",  attribute: "intelligence", options: "LinguisticsOptions"},
}

//add abbrevs for these
ROGUETRADER.commonLoreOptions = {
  "custom"            : {name: "CUSTOM",                    desc:"CUSTOM"},
  "adeptasororitas"   : {name: "Adepta Sororitas",          desc:"Knowledge of the women of the Adepta Sororitas and their spiritual culture, as well as their highly specialised equipment"},
  "adeptusarbites"    : {name: "Adeptus Arbites",           desc:"Knowledge of its various arms and sub-sects, including details of rank structure, common procedures, and the basic tenets of Imperial Justice"},
  "adeptusastartes"   : {name: "Adeptus Astartes",          desc:"Information concerning the physiologically and psychologically modified Space Marines, the Imperium’s most potent defenders. Few outside their ranks gain such knowledge, which can include the culture of a Chapter and its history, wargear, unusual physiology, and battle cants."},
  "adeptusmechanicus" : {name: "Adeptus Mechanicus",        desc:"A general understanding of the symbols and practices that the Cult of the Machine God commonly uses."},
  "adeptusadmin"      : {name: "Adeptus Administratum",     desc:"Broad knowledge of the labyrinthine workings, rules, traditions, and dictates of the Adeptus Administratum."},
  "calixissector"     : {name: "Calixis Sector",            desc:"Information concerning the basic layout and history of the sector."},
  "chartistcaptains"  : {name: "Chartist Captains",         desc:"Knowledge of the merchant vessels across the Calixis & Koronus sectors, which complete centuries-long circuits through series of neighbouring worlds as the primary means of Imperial commerce."},
  "collegiatitanicus" : {name: "Collegia Titanicus",        desc:"Familiarity with those who control the Battle Titans of the Adeptus Mechanicus, some of the most potent planet-bound weapons known to the Imperium."},
  "ecclesiarchy"      : {name: "Ecclesiarchy",              desc:"Understanding of the structure of the Adeptus Ministorum and its role in the worship of the Emperor."},
  "imperialcreed"     : {name: "Imperial Creed",            desc:"Knowledge of the rites, practices, and personages of the Imperial Cult, the most common observances and festivals in honour of the Emperor."},
  "astramilitarum"    : {name: "Astra Militarum",           desc:"Basic information about the ranking system, logistics, structure, and basic tactical and strategic practices of the Imperial Guard, as well as particularly famed regiments."},
  "imperialnavy"      : {name: "Imperial Navy",             desc:"Basic information about the ranks, customs, uniforms, and particular traditions of the Imperial Navy, as well as famous admirals and ships."},
  "imperium"          : {name: "Imperium",                  desc:"Knowledge of the segmenta, sectors, and best-known worlds of the Imperium."},
  "collegiatitanicus" : {name: "Collegia Titanicus",        desc:"Familiarity with those who control the Battle Titans of the Adeptus Mechanicus, some of the most potent planet-bound weapons known to the Imperium."},
  "kaitaran"          : {name: "Kai'ta'ran Sept",           desc:"Knowledge of the Sept’s society, organizations, general history, and important figures. "},
  "koronussector"     : {name: "Koronus Sector",            desc:"Information concerning the basic layout and history of the sector."},
  "marianrepublic"    : {name: "Marian Colonial Republic",  desc:"Knowledge of MCR society, organizations, general history, and important figures. "},
  "navigators"        : {name: "Navigators",                desc:"Information regarding these valued mutants who are essential for Warp travel and the Imperium’s survival, including the various Navis Nobilite Houses operating within the Calixis and Koronus sectors, their lineages, and methodologies."},
  "ostrakis"          : {name: "Ostrakis Polity",           desc:"Knowledge of Enclaver society, organizations, general history, and important figures."},
  "patavianreach"     : {name: "Patavian Reach",            desc:"Information concerning the basic layout and history of the region."},
  "planetarydef"      : {name: "Planetary Defence Forces",  desc:"Information concerning a planet’s standing force dedicated to defending itself as well as assisting any nearby Imperial systems. This includes composition, tactics, and equipment, which might vary substantially based on the culture and technological make-up of the world."},
  "roguetraders"      : {name: "Rogue Traders",             desc:"Information concerning the many Rogue Trader dynasties operating within the sector and beyond in search of profit and power."},
  "scholaprogenium"   : {name: "Schola Progenium",          desc:"A strong familiarity with the Schola Progenium, which trains and indoctrinates the many Imperial orphans and prepares them for lives of faithful service as elite troopers in the Militarum Tempestus, Commissars in the Officio Prefectus, or adepts in one of the Imperium’s many other divisions."},
  "skaaldir"          : {name: "Skaaldir Clans",            desc:"Knowledge of the different clans of the Skaald; their worlds, fleets, traditions, etc."},
  "demiurg"           : {name: "Srry'tok Collective",       desc:"Knowledge of Srry’tok society, organizations, general history, and important figures."},
  "tauempire"         : {name: "Tau Empire",                desc:"Knowledge of life in the Tau Empire, as relates to both the Tau species and the numerous other races that exist as vassals, allies, and auxiliaries within their domain."},
  "ostrakis"          : {name: "Ostrakis Polity",           desc:"Knowledge of Enclaver society, organizations, general history, and important figures."},
  "tech"              : {name: "Tech",                      desc:"An understanding of simple litanies and rituals to soothe and appease machine spirits."},
  "underworld"        : {name: "Underworld",                desc:"The Acolyte is familiar with basic criminal elements and groups, such as pickpockets, debt-carnivores, and the like."},
  "war"               : {name: "War",                       desc:"Knowledge of great battles, notable commanders, heroes, and famous stratagems employed by those who fight in the endless battles for and against the Imperium."},
};

//add abbrevs for these
ROGUETRADER.ForbiddenLoreOptions = {
  "custom"            : {name: "CUSTOM",                  desc:"CUSTOM"},
  "archaeotech"       : {name: "Archaeotech",             desc:"Knowledge of the great, lost tech devices of times past, and clues to their mysterious functions and purposes."},
  "chaosspacemarines" : {name: "Chaos Space Marines",     desc:"Information concerning those Adeptus Astartes who turned traitor, as well as the paths they embrace and the equipment they use."},
  "criminalcartels"   : {name: "Criminal Cartels",        desc:"Information regarding organised groups that flout the Emperor’s Law, such as those engaging in the Faceless Trade of proscribed artefacts."},
  "daemonology"       : {name: "Daemonology",             desc:"Terrible knowledge about some of the most infamous Warp entities and their twisted physical manifestations."},
  "enclaves"          : {name: "The Enclaves",            desc:"Knowledge of the terrible and hidden secrets of the Ostrakis enclaves."},
  "heresy"            : {name: "Heresy",                  desc:"Wisdom concerning acts and practices deemed anathema by the Imperium, plus the most contemptible heretics of history and their infamous and deplorable acts."},
  "horusheresy"       : {name: "Horus Heresy",            desc:"The origins and history of the 10,000 year long struggle between the forces of the Ruinous Powers and the Imperium of Man."},
  "iga"               : {name: "The Iga",                 desc:"Knowledge of the Reach’s reclusive assassins."},
  "inquisition"       : {name: "Inquisition",             desc:"Understanding the secretive organisation of the Imperium, its common tenets and famous Inquisitors."},
  "machinecult"       : {name: "Machine Cult",            desc:"Knowledge of the secret rites and knowledge long guarded by the Adeptus Mechanicus."},
  "mutants"           : {name: "Mutants",                 desc:"The study of stable and unstable mutations within humanity, their cancerous influence and mutagenic development over time, and some of the studies and tomes on the topic."},
  "officioassassin"   : {name: "Officio Assassinorum",    desc:"This highly secretive agency exists to eliminate powerful, often singular threats to the Imperium, such as renegade planetary governors or apostate preachers. Those who dare study the organisation may become familiar with their techniques and wargear."},
  "pirates"           : {name: "Pirates",                 desc:"Knowledge of the scourges of the Warp lanes throughout the Expanse and the Reach, their tactics, infamous vessels, and notorious captains."},
  "psykers"           : {name: "Psykers",                 desc:"Skill in identifying psykers, the effects of their unnatural powers, their dangers, and the general extent of their capabilities."},
  "rvarrnaschema"     : {name: "R'varrna Schema",         desc:"The proscribed secrets behind Tau technology, from personal equipment to battlesuits and voidships."},
  "skaaldirrites"     : {name: "Skaaldir Bloodrites",     desc:"The secret lores of the Skaaldir tribes, including their customs, origins, and settlement locations."},
  "warp"              : {name: "The Warp",                desc:"An understanding of the energy of the Immaterium, its interaction and interrelation with realspace, and how its tides and eddies affect travel between the stars."},
  "vail"              : {name: "Knights of Vail",         desc:"Knowledge of the interdicted world of Vail, along with the secrets of the knights of Vail."},
  "xenos"             : {name: "Xenos:General",           desc:"Rudimentary knowledge of the minor and major alien species known to the Imperium, the threat they pose to Mankind, and their general appearance."},
  "xenoseldari"       : {name: "Xenos:Aeldari",           desc:"Knowledge of the enigmatic Aeldari."},
  "xenosdrukhari"     : {name: "Xenos:Drukhari",          desc:"Knowledge of the brutal Drukhari."},
  "xenosdemiurg"      : {name: "Xenos:Demiurg",           desc:"Knowledge of the squat Demiurg."},
  "xenosegarian"      : {name: "Xenos:Egarian",           desc:"Knowledge of the long-dead Egarians."},
  "xenosgscult"       : {name: "Xenos:GSC",               desc:"Knowledge of the mysterious Genestealer Cults."},
  "xenosgkroot"       : {name: "Xenos:Kroot",             desc:"Knowledge of the secretive Kroot Kindreds"},
  "xenosnecrons"      : {name: "Xenos:Necrons",           desc:"Knowledge of the cryptic Necrons."},
  "xenosorks"         : {name: "Xenos:Orks",              desc:"Knowledge of the infamous Orks."},
  "xenostau"          : {name: "Xenos:Tau",               desc:"Knowledge of the stoic Tau."},
  "xenostyranid"      : {name: "Xenos:Tyranids",          desc:"Knowledge of the savage Tyranid."},
  "xenosvotann"       : {name: "Xenos:Votann",            desc:"Knowledge of the nascent Leagues of Votann"},
  "xenosyuvath"       : {name: "Xenos:Yu'Vath",           desc:"Knowledge of the blighted Yu'Vath."},
};

//add abbrevs for these
ROGUETRADER.ScholasticLoreOptions = {
  "custom"            : {name: "CUSTOM",                  desc:"CUSTOM"},
  "anatomy"           : {name: "Anatomy",                 desc:"An academic understanding of human biology and physiology."},
  "archaic"           : {name: "Archaic",                 desc:"An understanding of the Imperium’s dark past, its proscribed eras and how the long millennia have changed the face of mankind."},
  "astromancy"        : {name: "Astromancy",              desc:"A knowledge of stars, singularities, and the worlds around them, as well as theoretical understanding of how to use magnascopes, astrolithic charts, and the like."},
  "beasts"            : {name: "Beasts",                  desc:"An understanding of the genus and families of animals and familiarity with the characteristics and appearances of the many semi-sentient creatures to be found across the sector."},
  "bureaucracy"       : {name: "Bureaucracy",             desc:"A familiarity with the rules and regulations involved with Askellian governments, particularly the Adeptus Administratum, and their many and varied departments, bureaus, and polices."},
  "chymistry"         : {name: "Chymistry",               desc:"A knowledge of chemicals, their alchemical applications in a number of uses, and their prevalence or scarcity throughout the Imperium."},
  "cryptology"        : {name: "Cryptology",              desc:"An understanding of codes, ciphers, cryptographs, secret languages, and numerical keys. This may be used to either create or decipher encryptions."},
  "heraldry"          : {name: "Heraldry",                desc:"A grasp of the principles and devices of heraldry, as well as a knowledge of the most common seals and heraldic devices used by the Askellon’s noble houses and families."},
  "impcreed"          : {name: "Imperial Creed",          desc:"An understanding of the specific rituals and practices of the Ecclesiarchy, from the traditional construction of their temples to specific points from its texts. This information may be used to conduct the rituals for others."},
  "impwarrants"       : {name: "Imperial Warrants",       desc:"Information concerning the establishment, legal scope, and use of the warrants granted to Rogue Traders, as well as the best-known and dynastic warrants of the Imperium."},
  "judgment"          : {name: "Judgment",                desc:"Knowledge of the proper sentences for the multitude of crimes and heresies punishable by Imperial law."},
  "legend"            : {name: "Legend",                  desc:"Going beyond archaic knowledge, this encompasses momentous portions of mythic history, such as the Dark Age of Technology, the Age of Strife, the Great Crusade, and the Horus Heresy, retold in the form of epic, apocryphal fables."},
  "mythsreach"        : {name: "Myths of the Reach",      desc:"Lore concerning the legends and old stories told across the Reach."},
  "navisnobilite"     : {name: "Navis Nobilite",          desc:"Lore concerning the family trees, contracts, and histories of the great houses of the Navigators. "},
  "numerology"        : {name: "Numerology",              desc:"An understanding of the mysterious link between numbers and the physical universe, from low kharmic theory to the infamous Kappellax Correlation."},
  "occult"            : {name: "Occult",                  desc:"An understanding of obscure and hermetic (though not clearly heretical) rituals, theories, and superstitions, as well as the better-known mystical uses of occult items."},
  "philosophy"        : {name: "Philosophy",              desc:"Knowledge concerning the theories of thought, belief, existence, and other intangibles. As it also includes logic and debate, it may be used for crafting arguments or creating philosophical tracts."},
  "tacticaimp"        : {name: "Tactica Imperialis",      desc:"The codified military doctrines of the Imperial Guard and Imperial Navy, as well as other systems of troop deployment and battle techniques used by the Imperium. This knowledge may be used to devise a battle plan or deduce the likely flow of war fought by Imperial forces."},
  "tauemp"            : {name: "Tau Empire",              desc:"Beyond the basic facts and cultural cues of the Tau Empire, the complexities of Tau society often bafﬂe even the most skilled xenographers. This Skill represents a knowledge of the structures, regulations, and hierarchies of Tau society on an academic level."},
};

//add abbrevs for these
ROGUETRADER.LinguisticsOptions = {
  "custom"            : {name: "CUSTOM",                  desc:"CUSTOM"},
  "lowgothic"         : {name: "Low Gothic",              desc:"The common tongue of the Imperium."},
  "highgothic"        : {name: "High Gothic",             desc:"The archaic older language of the Imperium. Typically limited to contemporary nobility and ancient documents."},
};

//add abbrevs for these
ROGUETRADER.TradeOptions = {
  "custom"            : {name: "CUSTOM",            desc:"CUSTOM"},
  "agri"              : {name: "Agri",              desc:"Used to grow, care for, and harvest crops and animals."},
  "archaeologist"     : {name: "Archaeologist",     desc:"Used to locate, examine, and analyse ancient ruins and artefacts."},
  "armorer"           : {name: "Armorer",           desc:"Used to design, upgrade, and forge personal weaponry and armor."},
  "astrographer"      : {name: "Astrographer",      desc:"Used to create two- and three-dimensional representations of stellar locations and Warp routes."},
  "chymist"           : {name: "Chymist",           desc:"Used to create poisons, drugs, and a wide variety of other compounds."},
  "cryptographer"     : {name: "Cryptographer",     desc:"Used to create or decode complicated ciphers, codes, and other puzzles."},
  "cook"              : {name: "Cook",              desc:"Used to cook meals and determine if scavenged food is edible."},
  "explorator"        : {name: "Explorator",        desc:"Used in the exploration of unknown stellar regions."},
  "linguist"          : {name: "Linguist",          desc:"Used to learn or decipher new languages, both spoken and written, and even create new ones in some cases."},
  "loremancer"        : {name: "Loremancer",        desc:"Used to recount events in a variety of ways, from dry recitations or texts to epic operas or statuary."},
  "mechwright"        : {name: "Mechwright",        desc:"Used to design, upgrade, and manufacture Tau mechs (and retrofit mech equipment)."},
  "morticator"        : {name: "Morticator",        desc:"Used to prepare, preserve, and often render down corpse remains into ingredients for a variety of preparations."},
  "performancer"      : {name: "Performancer",      desc:"Used to perform for audiences in a variety of entertaining art forms, often using dance, song, and poetry."},
  "prospector"        : {name: "Prospector",        desc:"Used to find and identify valuable minerals."},
  "scrimshawer"       : {name: "Scrimshawer",       desc:"Used to inscribe patterns, text, and art onto a variety of materials."},
  "sculptor"          : {name: "Sculptor",          desc:"Used to create inspiring works of art in stone, metal, and other materials, often as part of Imperial edifices."},
  "soothsayer"        : {name: "Soothsayer",        desc:"Used to “foretell” the future by a number of interpretative arts, though its effectiveness is suspect."},
  "technomat"         : {name: "Technomat",         desc:"Used to maintain and repair technological devices, but through rote memorization rather than true understanding or comprehension."},
  "voidfarer"         : {name: "Voidfarer",         desc:"Used in the day-to-day operation, logistics, and defence of starships."},
  "voidwright"        : {name: "Voidwright",        desc:"Used to design, upgrade, and manufacture void-capable vessels."},
};

ROGUETRADER.aptitudes = {
  "custom"          : "CUSTOM",
  "general"         : "General",
  "willpower"       : "Willpower",
  "defense"         : "Defense",
  "weaponskill"     : "Weapon Skill",
  "ballisticskill"  : "Ballistic Skill",
  "intelligence"    : "Intelligence",
  "tech"            : "Tech",
  "fieldcraft"      : "Fieldcraft",
  "psyker"          : "Psyker",
  "strength"        : "Strength",
  "finesse"         : "Finesse",
  "offense"         : "Offense",
}

ROGUETRADER.CoreTalents = {
"customt1"                  : {name: "CUSTOM TIER 1",             tier: 1,source: "CUSTOM", aptitudes:["custom","custom"],               prereqs: "CUSTOM",                                    shortdesc:"CUSTOM",                               desc: "CUSTOM"},
"customt2"                  : {name: "CUSTOM TIER 2",             tier: 2,source: "CUSTOM", aptitudes:["custom","custom"],               prereqs: "CUSTOM",                                    shortdesc:"CUSTOM",                               desc: "CUSTOM"},
"customt3"                  : {name: "CUSTOM TIER 3",             tier: 3,source: "CUSTOM", aptitudes:["custom","custom"],               prereqs: "CUSTOM",                                    shortdesc:"CUSTOM",                               desc: "CUSTOM"},
"ambidextrous": {name: "Ambidextrous",tier: 1,source: "DH2",aptitudes:["weaponskill","ballisticskill"],prereqs: "Agi 30",shortdesc:"Reduce penalties for using two weapons.",desc: "This talent does not represent true ambidexterity so much as sufficient training with both hands to make the distinction moot. When combined with Two-Weapon Wielder talent, the penalty for making attacks with both weapons in the same turn drops to –10."},
"blindfighting": {name: "Blind Fighting",tier: 1,source: "DH2",aptitudes:["perception","fieldcraft"],prereqs: "Per 30",shortdesc:"Eliminates melee combat penalties for obscured vision.",desc: "Years of practice and development of his other senses allows the Acolyte to fight in close combat without the benefit of sight. He ignores all penalties for fighting with a melee weapon while suffering from obscured vision, permitting him to fight in fog, smoke, or darkness more effectively. See page 229 for a full list of normal penalties based on lighting and vision. Note this talent only improves his chances to hit with melee weapons, and has no effect on ranged weapon attacks."},
"bodyguard": {name: "Bodyguard",tier: 1,source: "Beyond",aptitudes:["agility","defence"],prereqs: "Agi 35",shortdesc:"Take an attack that would hit an ally.",desc: ""},
"catfall": {name: "Catfall",tier: 1,source: "DH2",aptitudes:["agility","fieldcraft"],prereqs: "Agi 30",shortdesc:"Reduce falling damage.",desc: "Gymnastic ability and natural balance enables the Acolyte to fall great distances without harm. He automatically reduces the effective distance of all falls by a number of metres equal to his Agility bonus, ignoring this distance as if it did not exist. He also adds +20 to his Acrobatics skill tests when using the Jump special skill use, as it pertains to reducing damage from falling."},
"cluesfromthecrowds": {name: "Clues from the Crowds",tier: 1,source: "DH2",aptitudes:["general","social"],prereqs: "Fel 30",shortdesc:"Can re-roll a test made to gather information froma group.",desc: ""},
"diehard": {name: "Die Hard",tier: 1,source: "DH2",aptitudes:["willpower","defence"],prereqs: "WP 40",shortdesc:"Test Willpower to avoid Fatigue from Blood Loss.",desc: "Through either mental resolve or sheer stubbornness, the Acolyte refuses to fall. When this character would suffer a level of Fatigue due to the Blood Loss condition, he makes a Challenging (+0) Willpower test; if he succeeds, he does not suffer a level of Fatigue."},
"disarm": {name: "Disarm",tier: 1,source: "DH2",aptitudes:["weaponskill","defence"],prereqs: "Agi 30",shortdesc:"Force opponent to drop weapon.",desc: "The Acolyte can wrest weapons from his opponents’ hands through practised technique or brute force. As a Full Action, the character may make an Opposed Weapon Skill test against one target with whom he is engaged. If the Acolyte wins the test, the enemy drops his weapon to the ground. Should the Acolyte score three or more degrees of success, he can take the enemy’s weapon from him."},
"doubleteam": {name: "Double Team",tier: 1,source: "DH2",aptitudes:["general","offence"],prereqs: "None",shortdesc:"Gain additional +10 for outnumbering opponent.",desc: ""},
"enemy": {name: "Enemy",tier: 1,source: "DH2",aptitudes:["general","social"],prereqs: "None",shortdesc:"An organization or group particularly despises the character.",desc: ""},
"flagellant": {name: "Flagellant",tier: 1,source: "Within",aptitudes:["offence","toughness"],prereqs: "Willpower 30",shortdesc:"Gain fatigue to gain +10 bonus to willpower based tests.",desc: ""},
"ferricsummons": {name: "Ferric Summons",tier: 1,source: "DH2",aptitudes:["willpower","tech"],prereqs: "Ferric Lure Implants, Mechanicus Implants",shortdesc:"Can summon larger metallic objects.",desc: ""},
"frenzy": {name: "Frenzy",tier: 1,source: "DH2",aptitudes:["strength","offence"],prereqs: "None",shortdesc:"Enter psychotic rage to gain combat bonuses.",desc: ""},
"grenadier": {name: "Grenadier",tier: 1,source: "Without",aptitudes:["ballisticskill","finesse"],prereqs: "Ballistic Skill 35",shortdesc:"Reduce the distance scattered up to half BS bonus.",desc: ""},
"ironjaw": {name: "Iron Jaw",tier: 1,source: "DH2",aptitudes:["toughness","defence"],prereqs: "T 40",shortdesc:"Test Toughness to overcome Stunning.",desc: ""},
"jaded": {name: "Jaded",tier: 1,source: "DH2",aptitudes:["willpower","defence"],prereqs: "WP 40",shortdesc:"Ignore mundane horrors.",desc: ""},
"keenintuition": {name: "Keen Intuition",tier: 1,source: "DH2",aptitudes:["perception","social"],prereqs: "Int 35",shortdesc:"Can retry Awareness test once with –10 modifier.",desc: ""},
"leapup": {name: "Leap Up",tier: 1,source: "DH2",aptitudes:["agility","general"],prereqs: "Agi 30",shortdesc:"Stand as a Free Action.",desc: ""},
"leapingdodge": {name: "Leaping Dodge",tier: 1,source: "Without",aptitudes:["agility","defence"],prereqs: "Agi 35, Dodge +10",shortdesc:"May use dodge instead of agility against spray weapons.",desc: ""},
"mountedwarriorws": {name: "Mounted Warrior WS",tier: 1,source: "Within",aptitudes:["weaponskill","offence"],prereqs: "Operate+10 or Survival+10, BS or WS 30",shortdesc:"reduces any penalty for making Melee attacks from a moving vehicle or mount by 10.",desc: ""},
"mountedwarriorbs": {name: "Mounted Warrior BS",tier: 1,source: "Within",aptitudes:["ballisticskill","offence"],prereqs: "Operate+10 or Survival+10, BS or WS 30",shortdesc:"reduces any penalty for making Ranged attacks from a moving vehicle or mount by 10.",desc: ""},
"nowheretohide": {name: "Nowhere to Hide",tier: 1,source: "DH2",aptitudes:["perception","offence"],prereqs: "Per 30",shortdesc:"Can add DoS from the attack to reduce armour value of cover.",desc: ""},
"peer": {name: "Peer",tier: 1,source: "DH2",aptitudes:["fellowship","social"],prereqs: "Fel 30",shortdesc:"Character has good reputation amongst chosen group.",desc: ""},
"quickdraw": {name: "Quick Draw",tier: 1,source: "DH2",aptitudes:["agility","finesse"],prereqs: "None",shortdesc:"Draw weapon as Free Action.",desc: ""},
"rapidreload": {name: "Rapid Reload",tier: 1,source: "DH2",aptitudes:["agility","fieldcraft"],prereqs: "None",shortdesc:"Reduce reload time.",desc: ""},
"resistance": {name: "Resistance",tier: 1,source: "DH2",aptitudes:["toughness","defence"],prereqs: "None",shortdesc:"Gain +10 bonus to particular resistance test.",desc: ""},
"skilledrider": {name: "Skilled Rider",tier: 1,source: "Without",aptitudes:["agility","fieldcraft"],prereqs: "Operate+10",shortdesc:"Allows for agility test to Mount or Dismount a vehicle as a FA.",desc: ""},
"soundconstitution": {name: "Sound Constitution",tier: 1,source: "DH2",aptitudes:["toughness","general"],prereqs: "None",shortdesc:"Gain an additional wound.",desc: ""},
"takedown": {name: "Takedown",tier: 1,source: "DH2",aptitudes:["weaponskill","offence"],prereqs: "None",shortdesc:"Make special attack to stun opponent.",desc: ""},
"technicalknock": {name: "Technical Knock",tier: 1,source: "DH2",aptitudes:["intelligence","tech"],prereqs: "Int 30",shortdesc:"Un-jam gun as Half Action.",desc: ""},
"warpsense": {name: "Warp Sense",tier: 1,source: "DH2",aptitudes:["perception","psyker"],prereqs: "Psy Rating, Psyniscience, Per 30",shortdesc:"Allows Psyniscience test as Free Action.",desc: ""},
"weapontech": {name: "Weapon-Tech",tier: 1,source: "DH2",aptitudes:["intelligence","tech"],prereqs: "Tech Use +10, Int 40",shortdesc:"Increase potency of advanced weaponry.",desc: ""},
"weapontraining": {name: "Weapon Training",tier: 1,source: "DH2",aptitudes:["general","finesse"],prereqs: "None",shortdesc:"Use Weapon Group without penalty.",desc: ""},
"ambassadorimperialis": {name: "Ambassador Imperialis",tier: 2,source: "Without",aptitudes:["perception","social"],prereqs: "Agi 30",shortdesc:"Reduces penalty's and allow re-rolls to Interaction skill tests for dealing with xenos.",desc: ""},
"archivator": {name: "Archivator",tier: 2,source: "Without",aptitudes:["knowledge","perception"],prereqs: "Per 30",shortdesc:"Allow re-rolls at -10 on Scholastic Lore or Forbidden Lore test when utilizing sources of recorded information.",desc: ""},
"armourmonger": {name: "Armour-Monger",tier: 2,source: "DH2",aptitudes:["intelligence","tech"],prereqs: "Agi 35",shortdesc:"Increase the efficacy of physical armour.",desc: "The Acolyte is a skilled armourer, and constantly tinkers and improves his armour, or keeps it in pristine shape by repairing the slightest damage it sustains. With years of training, he has even learned to enhance the protection afforded by his armour and how to use it to its optimum. The character gains an extra amount of Armour points equal to his Intelligence bonus, which he can distribute to any locations that his armour would normally cover, as long as he has at least an hour each day to clean and repair it or make minor modifications. This bonus applies only to armour when the Acolyte is wearing it, as it combines his training with his skill at armoury."},
"battlerage": {name: "Battle Rage",tier: 2,source: "DH2",aptitudes:["strength","defence"],prereqs: "Agi 30",shortdesc:"Parry while frenzied.",desc: "Long experience and indomitable will have allowed the character to master the beast within, directing its rage while keeping his head, despite the howling bloodlust in his mind. The Acolyte can Parry while Frenzied, and can re-roll a failed test to snap out of Frenzy or resist entering Frenzy if he so chooses."},
"bulgingbiceps": {name: "Bulging Biceps",tier: 2,source: "DH2",aptitudes:["strength","offence"],prereqs: "Fel 30",shortdesc:"Remove bracing requirement from Heavy weapons.",desc: "Whereas a weaker man might be sent flying by the recoil of a heavy weapon, this Acolyte’s strong physique allows him to remain standing. He can fire a heavy weapon using Semi- Auto Burst or Full Auto Burst without bracing the weapon, and does not suffer the –30 penalty for failing to brace it. In addition, whenever he uses the Heft special use of the Athletics skill (see page 98) he can add +20 to his Athletics skill test to reflect his powerful musculature."},
"bulwarkoffaith": {name: "Bulwark of Faith",tier: 2,source: "Beyond",aptitudes:["defence","willpower"],prereqs: "WP 40",shortdesc:"When you pass a fear test against a daemon it take 1 damage.",desc: ""},
"combatmaster": {name: "Combat Master",tier: 2,source: "DH2",aptitudes:["weaponskill","defence"],prereqs: "Agi 30",shortdesc:"Opponents get no bonus for outnumbering the character.",desc: "The Acolyte’s weapon seems to be everywhere at once, keeping many more opponents at bay in close combat than would seem possible. Opponents fighting him in hand-to-hand combat gain no bonuses for Ganging Up (see page 229)."},
"constantvigilanceint": {name: "Constant Vigilance Int",tier: 2,source: "DH2",aptitudes:["perception","defence"],prereqs: "None",shortdesc:"Can use Int instead of Ag for Initiative rolls, and rolls two dice (picking higher) for the result.",desc: "From years of surviving ambushes and surprise attacks, the Acolyte is always ready for battle. His subconscious is alert to the slightest footstep or activation of a lasgun pack, and he acts often before he is fully aware of the threat. When this talent is taken, the character selects the Specialisation that matches the prerequisite (Perception or Intelligence) used in purchase. He can use the characteristic that matches that Specialisation when rolling for Initiative instead of his Agility value, and rolls two dice for the roll (picking the highest of the two for his score)."},
"constantvigilanceper": {name: "Constant Vigilance Per",tier: 2,source: "DH2",aptitudes:["perception","defence"],prereqs: "None",shortdesc:"Can use Per instead of Ag for Initiative rolls, and rolls two dice (picking higher) for the result.",desc: "From years of surviving ambushes and surprise attacks, the Acolyte is always ready for battle. His subconscious is alert to the slightest footstep or activation of a lasgun pack, and he acts often before he is fully aware of the threat. When this talent is taken, the character selects the Specialisation that matches the prerequisite (Perception or Intelligence) used in purchase. He can use the characteristic that matches that Specialisation when rolling for Initiative instead of his Agility value, and rolls two dice for the roll (picking the highest of the two for his score)."},
"contactnetwork": {name: "Contact Network",tier: 2,source: "DH2",aptitudes:["fellowship","leadership"],prereqs: "None",shortdesc:"Use Fellowship instead of Influence for Requisition tests.",desc: "Acolytes rely on a web of relationships, favours, debts, and obligations that can range from within a hab-block to spanning an entire system. Developing and exploiting this network properly allows them to gain access to weapons, travel berths, personnel, and other resources when needed; those who maximise their connections can ensure they are well-armed and well-prepared as they face a new heresy. An Acolyte with this talent can use his Fellowship characteristic in place of his Influence when making Requisition tests (see page 142)."},
"coordinatedinterrogation": {name: "Coordinated Interrogation",tier: 2,source: "DH2",aptitudes:["intelligence","social"],prereqs: "Willpower 30",shortdesc:"+10 bonus to all Interrogate tests, additional +5 for others who also have Coordinated Interrogation.",desc: "A trained Acolyte, especially when working in conjunction with fellow veteran Acolytes, can induce cooperation from even the most hardened of suspects and captured heretics. He gains a +10 bonus to all Interrogation tests, and gains an additional +5 for each other character participating in the interrogation who also has Coordinated Interrogation. This counts as test assistance, and thus also gains the standard assistance bonuses as per page 25."},
"counterattack": {name: "Counter Attack",tier: 2,source: "DH2",aptitudes:["weaponskill","defence"],prereqs: "Ferric Lure Implants, Mechanicus Implants",shortdesc:"May attack after successful Parry.",desc: "The Acolyte’s lightning ripostes are things of deadly beauty; swift and invisible as the wind. Once per turn, after successfully Parrying an opponent’s attack, this character may immediately make a Standard Attack action as a Free Action against that opponent using the weapon with which he Parried. The character suffers a –20 penalty on the Weapon Skill test for this attack"},
"coverup": {name: "Cover-Up",tier: 2,source: "DH2",aptitudes:["intelligence","knowledge"],prereqs: "None",shortdesc:"Can reduce Influence by 1 to gain 1d5 Subtlety.",desc: "Even the slightest whisper of the Inquisition’s presence can be enough to scatter suspected heretics and drive cults into hiding. To prevent the growth and spread of rumours, Acolytes use combinations of well-placed bribes, dire threats, and other means to keep their activities as secretive as possible. At the GM’s discretion, the character can reduce his Influence to increase his group’s Subtlety. For every point of Influence lost in this way, the Acolyte increases his warband’s Subtlety by 1d5."},
"daemonhunter": {name: "Daemonhunter",tier: 2,source: "Beyond",aptitudes:["offence","willpower"],prereqs: "Ballistic Skill 35",shortdesc:"Re-roll failed Awareness and Psyniscience Tests againts deamons attacks against daemons gain Proven (3).",desc: ""},
"daemonologist": {name: "Daemonologist",tier: 2,source: "Beyond",aptitudes:["psyker","willpower"],prereqs: "T 40",shortdesc:"+10 bonus to the Focus Power test against daemons.",desc: ""},
"denythewitch": {name: "Deny the Witch",tier: 2,source: "DH2",aptitudes:["willpower","defence"],prereqs: "WP 40",shortdesc:"Can use Willpower to Evade against psychic attacks.",desc: "The Acolyte draws on his faith and mental fortitude to act as his shield against those tainted by the Warp. The character may use his Willpower characteristic when making an Evasion Reaction against ranged or melee attacks against him made with psychic powers. When successfully evading an attack with an area of effect, the character does not move but instead is simply unaffected by the psychic power."},
"devastatingassault": {name: "Devastating Assault",tier: 2,source: "DH2",aptitudes:["weaponskill","offence"],prereqs: "Int 35",shortdesc:"A successful All Out Attack grants a second attack.",desc: "The Acolyte launches a furious attack on his foe, the rage of the Emperor powering his assault. Once per turn, after resolving an All Out Attack action that successfully hits, the character may make a second All Out Attack action against the same target as a Free Action, with the same bonuses and penalties as the first."},
"doubletap": {name: "Double Tap",tier: 2,source: "DH2",aptitudes:["finesse","offence"],prereqs: "Agi 30",shortdesc:"Successful first attack grants bonus to second attack.",desc: "The Acolyte is practiced in making dual attacks, and can almost subconsciously tell when his hits strike to best effect. When making a second ranged attack action in the same turn against the same target, he gains a +20 bonus to the attack test if his first attack scored one or more successful hits."},
"exoticweapontraining": {name: "Exotic Weapon Training",tier: 2,source: "DH2",aptitudes:["intelligence","finesse"],prereqs: "Agi 35, Dodge +10",shortdesc:"Gain proficiency with one exotic weapon type.",desc: ""},
"faceinacrowd": {name: "Face in a Crowd",tier: 2,source: "DH2",aptitudes:["fellowship","social"],prereqs: "Operate+10 or Survival+10, BS or WS 30",shortdesc:"Can use Fellowship instead of Agility when Shadowing.",desc: ""},
"fieldvivisection": {name: "Field Vivisection",tier: 2,source: "Without",aptitudes:["weaponskill","knowledge"],prereqs: "Operate+10 or Survival+10, BS or WS 30",shortdesc:"When using called shots the character may use Forbidden Lore (Xenos) skill, he makes a Medicae (WS) or Medicae (BS) test in place of the normal Weapon Skill test.",desc: ""},
"fieldvivisection": {name: "Field Vivisection",tier: 2,source: "Without",aptitudes:["ballisticskill","knowledge"],prereqs: "Operate+10 or Survival+10, BS or WS 30",shortdesc:"When using called shots the character may use Forbidden Lore (Xenos) skill, he makes a Medicae (WS) or Medicae (BS) test in place of the normal Ballistic Skill test.",desc: ""},
"hardtarget": {name: "Hard Target",tier: 2,source: "DH2",aptitudes:["agility","defence"],prereqs: "Per 30",shortdesc:"–20 to hit character when he Charges or Runs.",desc: ""},
"hardenedsoul": {name: "Hardened Soul",tier: 2,source: "Beyond",aptitudes:["defence","willpower"],prereqs: "Fel 30",shortdesc:"When gaining Corruption exchange up to have with insanity.",desc: ""},
"hardy": {name: "Hardy",tier: 2,source: "DH2",aptitudes:["toughness","defence"],prereqs: "None",shortdesc:"Character always heals as if Lightly Damaged.",desc: ""},
"hatred": {name: "Hatred",tier: 2,source: "DH2",aptitudes:["weaponskill","social"],prereqs: "None",shortdesc:"Gain +10 bonus to attack hated creatures.",desc: ""},
"hipshooting": {name: "Hip Shooting",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "None",shortdesc:"Characters may shoot when moving.",desc: ""},
"hotshotpilot": {name: "Hotshot Pilot",tier: 2,source: "Without",aptitudes:["agility","tech"],prereqs: "Operate+10",shortdesc:"Take fatigue to reduce or increase DOS on Operate Tests.",desc: ""},
"independenttargeting": {name: "Independent Targeting",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "None",shortdesc:"Fire at multiple targets more than 10 metres apart.",desc: ""},
"inescapableattack": {name: "Inescapable Attack",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "None",shortdesc:"Attacker imposes penalty on DoS from Evasion test equal to DoS his initial attack.",desc: ""},
"inescapableattack": {name: "Inescapable Attack",tier: 2,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "None",shortdesc:"Attacker imposes penalty on DoS from Evasion test equal to DoS his initial attack.",desc: ""},
"inspiringaura": {name: "Inspiring Aura",tier: 2,source: "Beyond",aptitudes:["leadership","willpower"],prereqs: "Int 30",shortdesc:"Can use the command skill on all allies.",desc: ""},
"ironresolve": {name: "Iron Resolve",tier: 2,source: "Beyond",aptitudes:["defence","willpower"],prereqs: "Psy Rating, Psyniscience, Per 30",shortdesc:"Re-roll failed fear and pinning with a -10 modifier.",desc: ""},
"killingstrike": {name: "Killing Strike",tier: 2,source: "DH2",aptitudes:["weaponskill","offence"],prereqs: "Tech Use +10, Int 40",shortdesc:"Spend Fate point to make melee attacks unavoidable.",desc: ""},
"lexographer": {name: "Lexographer",tier: 2,source: "Without",aptitudes:["intelligence","knowledge"],prereqs: "None",shortdesc:"Treats all unlearned languages as basic untrained skills.",desc: ""},
"luminenshock": {name: "Luminen Shock",tier: 2,source: "DH2",aptitudes:["weaponskill","tech"],prereqs: "Fellowship 35, Intelligence 35",shortdesc:"Character can discharge energy in melee attack.",desc: ""},
"maglevtranscendence": {name: "Maglev Transcendence",tier: 2,source: "DH2",aptitudes:["intelligence","tech"],prereqs: "Int 40",shortdesc:"Character can hover for longer periods of time.",desc: ""},
"marksman": {name: "Marksman",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "Int 35, Tech-Use, Trade (Armourer)",shortdesc:"No penalties for firing at long or extreme range.",desc: ""},
"mechadendriteuse": {name: "Mechadendrite Use",tier: 2,source: "DH2",aptitudes:["intelligence","tech"],prereqs: "Frenzy",shortdesc:"Gain ability to use certain Mechadendrites.",desc: ""},
"one-on-one": {name: "One-on-One",tier: 2,source: "Without",aptitudes:["finesse","weaponskill"],prereqs: "Str 45",shortdesc:"Gain half WS bonus on successful WS tests.",desc: ""},
"penitentpsyker": {name: "Penitent Psyker",tier: 2,source: "Within",aptitudes:["psyker","defence"],prereqs: "Willpower 45, Iron Faith",shortdesc:"Gain fatigue to gain bonus's to opposed willpower tests.",desc: ""},
"precisionkiller": {name: "Precision Killer",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "WS 30",shortdesc:"No penalty to making Called Shot in Ranged Combat.",desc: ""},
"precisionkiller": {name: "Precision Killer",tier: 2,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "WS 30",shortdesc:"No penalty to making Called Shot in Melee Combat.",desc: ""},
"prosanguine": {name: "Prosanguine",tier: 2,source: "DH2",aptitudes:["toughness","tech"],prereqs: "Int 35 or Per 35, Awareness +10",shortdesc:"Test to heal 1d5 damage.",desc: ""},
"purityofhatred": {name: "Purity of Hatred",tier: 2,source: "Within",aptitudes:["offence","willpower"],prereqs: "Cover-Up, Int 35",shortdesc:"Gain Vengeful (9) against those you hate.",desc: ""},
"ritesofbanishment": {name: "Rites of Banishment",tier: 2,source: "Beyond",aptitudes:["offence","willpower"],prereqs: "Str 40 or WP 40, Clues from the Crowds",shortdesc:"Once per round as a half actions the character can causes daemons to suffer -10 to their willpower tests.",desc: "It is often difficult to extract information from groups such as hive gangs or Administratum scribes, as often numbers can bolster recalcitrance to questioning. A veteran Acolyte knows that such groups can hold critical information to complete an investigation, and can throw more effective nets when interrogating groups and reveal valued clues. Once per day, he can re-roll a test made to gather information from a group of people."},
"strongminded": {name: "Strong Minded",tier: 2,source: "DH2",aptitudes:["willpower","defence"],prereqs: "WS 40",shortdesc:"May reroll failed WP tests to resist psychic powers.",desc: ""},
"swiftattack": {name: "Swift Attack",tier: 2,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "Int 35",shortdesc:"May make multiple melee attacks.",desc: ""},
"taintedpsyker": {name: "Tainted Psyker",tier: 2,source: "Within",aptitudes:["knowledge","psyker"],prereqs: "Forbidden Lore (Daemonology), Willpower 40",shortdesc:"Gain corruption in exchange for bonus's to Focus Power tests.",desc: ""},
"twoweaponwielder": {name: "Two-Weapon Wielder",tier: 2,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "Psy rating 3, Willpower 45, Forbidden Lore (Daemonology)",shortdesc:"May fight with two ranged weapons.",desc: ""},
"twoweaponwielder": {name: "Two-Weapon Wielder",tier: 2,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "Psy rating 3, Willpower 45, Forbidden Lore (Daemonology)",shortdesc:"May fight with two melee weapons.",desc: ""},
"unarmedspecialist": {name: "Unarmed Specialist",tier: 2,source: "DH2",aptitudes:["strength","offence"],prereqs: "WP 35",shortdesc:"When fighting unarmed, attacks hit as Deadly Natural Weapons and user can re-roll damage.",desc: ""},
"warpconduit": {name: "Warp Conduit",tier: 2,source: "DH2",aptitudes:["willpower","psyker"],prereqs: "WS 35",shortdesc:"Spend Fate point to add 1d5 to psy rating.",desc: ""},
"whirlwindofdeath": {name: "Whirlwind of Death",tier: 2,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "Two-Weapon Wielder",shortdesc:"Make one attack for each melee opponent.",desc: ""},
"witchfinder": {name: "Witch Finder",tier: 2,source: "Within",aptitudes:["knowledge","perception"],prereqs: "None",shortdesc:"Gain the Psyniscience skill.",desc: ""},
"xenosavant": {name: "Xenosavant",tier: 2,source: "Without",aptitudes:["intelligence","knowledge"],prereqs: "Fel 35, Clues from the Crowds",shortdesc:"Treats all unlearned Forbidden Lore (Xenos) as basic untrained skills.",desc: ""},
"adamantiumfaith": {name: "Adamantium Faith",tier: 3,source: "DH2",aptitudes:["willpower","defence"],prereqs: "Ballistic Skill or Weapon Skill 40, Forbidden Lore (Xenos–Any), Medicae +10",shortdesc:"Reduces DoF from failed Pinning and Fear tests.",desc: "The Acolyte has become inured to horrors that would cripple lesser men. This might come from years of facing incoming fire, staring down the terrors of the Warp, or simply his absolute faith in the Emperor. He can subtract his Willpower bonus from his degrees of failure on a failed Fear or Pinning test. If this reduces the result to zero or less, he counts as having passed the Fear test with 1 degree of success."},
"aegisofcontempt": {name: "Aegis of Contempt",tier: 3,source: "Within",aptitudes:["defence","leadership"],prereqs: "Agi 40",shortdesc:"This character and allies can reduce corruption gained by 1 or spend a fatepoint to gain 0 corruption.",desc: ""},
"assassinstrike": {name: "Assassin Strike",tier: 3,source: "DH2",aptitudes:["weaponskill","fieldcraft"],prereqs: "Willpower 35, 10 Corruption",shortdesc:"After melee attack, test Acrobatics to move.",desc: "The character’s natural agility and graceful martial form turn him into a dervish of death in combat. After making a melee attack, a successful Challenging (+0) Acrobatics skill test allows the Acolyte to move at half rate as a Free Action. He may only make this move once per round, and the character’s opponent does not receive a free attack resulting from this move."},
"bastionofironwill": {name: "Bastion of Iron Will",tier: 3,source: "DH2",aptitudes:["willpower","psyker"],prereqs: "T 40",shortdesc:"Gain bonus for Opposed tests against psychic powers.",desc: "The Acolyte’s sheer willpower and psychic focus have become one and the same, over years of practice and training, such that their combined use is second nature. He adds 5 x his psy rating to any Opposed test he makes when defending against psychic powers."},
"blademaster": {name: "Blademaster",tier: 3,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "None",shortdesc:"Reroll missed attack, once per round.",desc: "The Acolyte’s mastery of bladed weapons and their martial disciplines has no peer. When attacking with any bladed weapon, including chainswords, axes, and power swords, he can re-roll one missed attack per round"},
"crushingblow": {name: "Crushing Blow",tier: 3,source: "DH2",aptitudes:["weaponskill","offence"],prereqs: "BS 40, Agi 40",shortdesc:"Add half WS bonus to damage inflicted in melee.",desc: "The Acolyte has the ability to focus his entire body into close combat attacks. He adds half his Weapon Skill bonus (rounding up) to damage he inflicts with melee attacks."},
"daemonicdisruption": {name: "Daemonic Disruption",tier: 3,source: "Beyond",aptitudes:["willpower","general"],prereqs: "Operate+10 or Survival+10",shortdesc:"Creatures with Warp Instability trait roll on test for Warp Instability, after a successful attack.",desc: ""},
"darksoul": {name: "Dark Soul",tier: 3,source: "Beyond",aptitudes:["toughness","willpower"],prereqs: "BS 40",shortdesc:"When gaining a mutation due to corruption, the character may choose to pass.",desc: ""},
"deathdealerbs": {name: "Deathdealer BS",tier: 3,source: "DH2",aptitudes:["perception","finesse"],prereqs: "BS 40, Per 35",shortdesc:"Add Per bonus to damage inflicted in combat.",desc: "This talent does not represent true ambidexterity so much as sufficient training with both hands to make the distinction moot. When combined with Two-Weapon Wielder talent, the penalty for making attacks with both weapons in the same turn drops to –10."},
"deathdealerws": {name: "Deathdealer WS",tier: 3,source: "DH2",aptitudes:["perception","finesse"],prereqs: "WS 40, Per 35",shortdesc:"Add Per bonus to damage inflicted in combat.",desc: "This talent does not represent true ambidexterity so much as sufficient training with both hands to make the distinction moot. When combined with Two-Weapon Wielder talent, the penalty for making attacks with both weapons in the same turn drops to –10."},
"delicateinterrogation": {name: "Delicate Interrogation",tier: 3,source: "DH2",aptitudes:["intelligence","finesse"],prereqs: "Halo of Command",shortdesc:"Reduce Subtlety loss by 1d5 when conducting an investigation.",desc: "Questioning suspects and witnesses is always a necessary part of any investigation. Such sessions must remain secretive or obscured, however, lest others learn of the Inquisition’s interest, and a variety of subterfuges, deceptions, and outright threats come into play to aid this effort. Whenever the Acolyte would decrease his warband’s Subtlety due to an interrogation, the amount of Subtlety lost is reduced by 1d5. If this results in a negative number, the Acolyte’s skilled efforts increase the warband’s Subtlety by 1."},
"divineprotection": {name: "Divine Protection",tier: 3,source: "Within",aptitudes:["general","finesse"],prereqs: "Resistance (Fear), Jaded",shortdesc:"Spray attacks do not harm allies.",desc: ""},
"eyeofvengeance": {name: "Eye of Vengeance",tier: 3,source: "DH2",aptitudes:["ballisticskill","offence"],prereqs: "WS 50",shortdesc:"Spend 1 Fate point to increase damage and penetration.",desc: ""},
"favouredbythewarp": {name: "Favoured by the War",tier: 3,source: "DH2",aptitudes:["willpower","psyker"],prereqs: "Linguistics (Any) +20",shortdesc:"Roll twice for Psychic Phenomena and choose result.",desc: ""},
"flashofinsight": {name: "Flash of Insight",tier: 3,source: "DH2",aptitudes:["perception","knowledge"],prereqs: "Luminen Capacitors, Mechanicus Implants",shortdesc:"Spend 1 Fate point to reveal a clue.",desc: ""},
"haloofcommand": {name: "Halo of Command",tier: 3,source: "DH2",aptitudes:["fellowship","leadership"],prereqs: "Maglev Coils, Mechanicus Implants",shortdesc:"Affect NPCs within 100xFelB metres with Social skills.",desc: ""},
"hammerblow": {name: "Hammer Blow",tier: 3,source: "DH2",aptitudes:["strength","offence"],prereqs: "BS 35",shortdesc:"Make a thunderous strike with a melee weapon.",desc: ""},
"hulldown": {name: "Hull Down",tier: 3,source: "Without",aptitudes:["agility","fieldcraft"],prereqs: "Mechanicus Implants",shortdesc:"Vehicle gains decreases size by 1 and gains cover against attacks.",desc: ""},
"infusedknowledge": {name: "Infused Knowledge",tier: 3,source: "DH2",aptitudes:["intelligence","knowledge"],prereqs: "Weapon Skill 40",shortdesc:"Know a little bit about everything.",desc: ""},
"instrumentofhiswill": {name: "Instrument of his Will",tier: 3,source: "Beyond",aptitudes:["offence","willpower"],prereqs: "Psy rating, Strong Minded, Willpower 40",shortdesc:"Increase damage by double your willpower against Daemons.",desc: ""},
"intothejawsofhell": {name: "Into the Jaws of Hell",tier: 3,source: "Within",aptitudes:["leadership","Willpower"],prereqs: "BS 40 or WS 40",shortdesc:"If the inquisitor passes a fear or pinning test, allies and servants reduce their degress of failure on the same test by the inquisitors fellowship bonus.",desc: ""},
"indomitable conviction": {name: "Indomitable Conviction",tier: 3,source: "Within",aptitudes:["leadership","willpower"],prereqs: "Autosanguine Implants, Mechanicus Implants",shortdesc:"This character and allies can reduce Insanity gained by 1 or spend a fatepoint to gain 0 insanity.",desc: ""},
"ironfaith": {name: "Iron Faith",tier: 3,source: "Beyond",aptitudes:["defence","willpower"],prereqs: "Hatred (Any)",shortdesc:"Grants immunity to the effects of the Baneful Presence trait.",desc: ""},
"lightningattack": {name: "Lightning Attack",tier: 3,source: "DH2",aptitudes:["weaponskill","finesse"],prereqs: "Common Lore (Imperial Creed) +10 or Forbidden Lore (Daemonology)",shortdesc:"Character may make many melee attacks with single roll.",desc: ""},
"luminenblast": {name: "Luminen Blast",tier: 3,source: "DH2",aptitudes:["ballisticskill","tech"],prereqs: "WP 30, Resistance (Psychic Powers)",shortdesc:"May discharge stored energy as a ranged attack.",desc: ""},
"mastery": {name: "Mastery",tier: 3,source: "DH2",aptitudes:["intelligence","knowledge"],prereqs: "WS 30",shortdesc:"May spend Fate point to succeed on test.",desc: ""},
"mightyshot": {name: "Mighty Shot",tier: 3,source: "DH2",aptitudes:["ballisticskill","offence"],prereqs: "Psy rating, Psyniscience +10, 10 Corruption",shortdesc:"Add half BS bonus to ranged damage rolls.",desc: ""},
"neverdie": {name: "Never Die",tier: 3,source: "DH2",aptitudes:["toughness","defence"],prereqs: "—",shortdesc:"Ignore penalties from Critical damage by spending Fate point.",desc: ""},
"preternaturalspeed": {name: "Preternatural Speed",tier: 3,source: "DH2",aptitudes:["agility","offence"],prereqs: "WP 50, T 50",shortdesc:"Double speed when charging.",desc: ""},
"pushthelimit": {name: "Push the Limit",tier: 3,source: "Without",aptitudes:["perception","tech"],prereqs: "WS 40, Agi 50",shortdesc:"Once per round, the character may add +20 to an Operate test .",desc: ""},
"sancticpurity": {name: "Sanctic Purity",tier: 3,source: "Beyond",aptitudes:["psyker","willpower"],prereqs: "Operate+10 or Survival+10",shortdesc:"May spend a fatepoint to negate psychic phenomena when using Sanctic Daemonology powers.",desc: ""},
"shieldwall": {name: "Shield Wall",tier: 3,source: "Beyond",aptitudes:["defence","weaponskill"],prereqs: "Daemonologist, Favoured by the Warp, Willpower 50",shortdesc:"Re-roll one failed Evasion test to Parry an attack per round.",desc: ""},
"sprint": {name: "Sprint",tier: 3,source: "DH2",aptitudes:["agility","fieldcraft"],prereqs: "Ambidextrous, WS 40",shortdesc:"Move more quickly in combat.",desc: ""},
"stepaside": {name: "Step Aside",tier: 3,source: "DH2",aptitudes:["agility","defence"],prereqs: "None",shortdesc:"Can make additional Dodge or Parry attempt.",desc: ""},
"superiorchirurgeon": {name: "Superior Chirurgeon",tier: 3,source: "DH2",aptitudes:["intelligence","fieldcraft"],prereqs: "Agi 40, Dodge or P",shortdesc:"Gain +20 to Medicae tests, bonuses to first aid tests.",desc: ""},
"targetselection": {name: "Target Selection",tier: 3,source: "DH2",aptitudes:["ballisticskill","finesse"],prereqs: "Rank 2 in Medicae skill",shortdesc:"May shoot into melee without penalty.",desc: ""},
"thundercharge": {name: "Thunder Charge",tier: 3,source: "DH2",aptitudes:["strength","offence"],prereqs: "BS 50",shortdesc:"Break enemies with armoured charge.",desc: ""},
"truegrit": {name: "True Grit",tier: 3,source: "DH2",aptitudes:["toughness","defence"],prereqs: "S 50",shortdesc:"Reduce Critical damage taken.",desc: ""},
"twoweaponmaster": {name: "Two-Weapon Master",tier: 3,source: "DH2",aptitudes:["finesse","offence"],prereqs: "T 40",shortdesc:"No penalties when fighting with two single-handed weapons.",desc: ""},
"warplock": {name: "Warp Lock",tier: 3,source: "DH2",aptitudes:["willpower","psyker"],prereqs: "Agi 45, Ambidextrous, BS 40 or WS 40, Two Weapon Wielder",shortdesc:"Ignore Psychic Phenomenon once per session.",desc: ""},
"weaponintuition": {name: "Weapon Intuition",tier: 3,source: "Without",aptitudes:["intelligence","finesse"],prereqs: "Psy Rating, Strong Minded, WP 50",shortdesc:"reduce the penalty for using a untrained weapon by 10.",desc: ""},

}

//TODO: alter to {name: } format instead
ROGUETRADER.WeaponClasses = {
  'melee'   : 'Melee',
  'thrown'  : 'Thrown',
  'pistol'  : 'Pistol',
  'basic'   : 'Basic',
  'heavy'   : 'Heavy',
  'vehicle' : 'Vehicle',
  'sniper'  : 'Sniper',
}

ROGUETRADER.WeaponClassesNew = {
  'melee'   : {name:'Melee',    },
  'thrown'  : {name:'Thrown',   },
  'pistol'  : {name:'Pistol',   },
  'basic'   : {name:'Basic',    },
  'heavy'   : {name:'Heavy',    },
  'vehicle' : {name:'Vehicle',  },
  'sniper'  : {name:'Sniper',   },
}

//TODO: configure lists to filter valid options by category
ROGUETRADER.WeaponSpecs = {
  'bolt'            :{name:'Bolt',              valid:'ranged'},
  'chain'           :{name:'Chain',             valid:'melee'},
  'flame'           :{name:'Flame',             valid:'ranged'},
  'las'             :{name:'Las',               valid:'ranged'},
  'launcher'        :{name:'Launcher',          valid:'ranged'},
  'melta'           :{name:'Melta',             valid:'ranged'},
  'plasma'          :{name:'Plasma',            valid:'ranged'},
  'power'           :{name:'Power',             valid:'ranged'},
  'lowtech'         :{name:'Low-Tech',          valid:'all'},
  'shock'           :{name:'Shock',             valid:'melee'},
  'solidprojectile' :{name:'Solid Projectile',  valid:'ranged'},
}

ROGUETRADER.WeaponReloads = {
  'na'      :'N/A',
  'free'    :'Free',
  'reaction':'Reaction',
  'half'    :'Half',
  'full'    :'Full',
  '2full'   :'2 Full',
  '3full'   :'3 Full',
}

ROGUETRADER.WeaponSpecialQualities = {
  'na'              : {name:'N/A',            hasval:false},
  'accurate'        : {name:'Accurate',       hasval:false},
  'balanced'        : {name:'Balanced',       hasval:false},
  'blast'           : {name:'Blast',          hasval:true},
  'concussive'      : {name:'Concussive',     hasval:true},
  'corrosive'       : {name:'Corrosive',      hasval:false},
  'crippling'       : {name:'Crippling',      hasval:true},
  'defensive'       : {name:'Defensive',      hasval:false},
  'felling'         : {name:'Felling',        hasval:true},
  'flame'           : {name:'Flame',          hasval:false},
  'flexible'        : {name:'Flexible',       hasval:false},
  'force'           : {name:'Force',          hasval:false},
  'graviton'        : {name:'Graviton',       hasval:false},
  'hallucinogenic'  : {name:'Hallucinogenic', hasval:true},
  'haywire'         : {name:'Haywire',        hasval:true},
  'inaccurate'      : {name:'Inaccurate',     hasval:false},
  'indirect'        : {name:'Indirect',       hasval:true},
  'lance'           : {name:'Lance',          hasval:false},
  'maximal'         : {name:'Maximal',        hasval:false},
  'melta'           : {name:'Melta',          hasval:false},
  'overheats'       : {name:'Overheats',      hasval:false},
  'powerfield'      : {name:'Power Field',    hasval:false},
  'primitive'       : {name:'Primitive',      hasval:true},
  'proven'          : {name:'Proven',         hasval:true},
  'razorsharp'      : {name:'Razor Sharp',    hasval:false},
  'recharge'        : {name:'Recharge',       hasval:false},
  'reliable'        : {name:'Reliable',       hasval:false},
  'sanctified'      : {name:'Sanctified',     hasval:false},
  'scatter'         : {name:'Scatter',        hasval:false},
  'shocking'        : {name:'Shocking',       hasval:false},
  'smoke'           : {name:'Smoke',          hasval:true},
  'snare'           : {name:'Snare',          hasval:true},
  'spray'           : {name:'Spray',          hasval:false},
  'storm'           : {name:'Storm',          hasval:false},
  'tearing'         : {name:'Tearing',        hasval:false},
  'toxic'           : {name:'Toxic',          hasval:true},
  'twinlinked'      : {name:'Twin-Linked',    hasval:false},
  'unbalanced'      : {name:'Unbalanced',     hasval:false},
  'unreliable'      : {name:'Unreliable',     hasval:false},
  'unwieldy'        : {name:'Unwieldy',       hasval:false},
  'vengeful'        : {name:'Vengeful',       hasval:true}
}

ROGUETRADER.ItemOrigins = {
  'custom'  :'CUSTOM',
  'human'   :'Human(*)',
  'imperial':'Human(Imperial)',
  'xenos'   :'Xenos(?)'
}

ROGUETRADER.ItemCraftsmanship = {
  'poor'  : 'Poor',
  'normal': 'Normal',
  'good'  : 'Good',
  'best'  : 'Best'
}
